name: Test coverage

on:
  workflow_dispatch:
  pull_request:
   branches: [ develop ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
     # Step to run automated tests
    - uses: actions/checkout@v1
    - name: Bundle Install
      run: bundle install
      
    - name: Generate project
      run: |
         curl -L -o ./tuist.zip https://github.com/tuist/tuist/releases/download/1.39.1/tuist.zip
         unzip ./tuist.zip -d .tuist-bin
         .tuist-bin/tuist generate
         
    - name: Clear derived data
      run: |
        fastlane run clear_derived_data

    - name: Run tests
      run: |
        fastlane tests --verbose
